# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pizzas.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_auto_20170524_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comments', to='pizzas.Pizza'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.IntegerField(validators=[pizzas.models.validate_even]),
        ),
    ]
