# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pizzas.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0008_auto_20170525_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comments', to='pizzas.Pizza', verbose_name='Pizza'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.IntegerField(validators=[pizzas.models.validate_even], verbose_name='Puntuación'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=140, verbose_name='Valoración'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.CharField(max_length=250, null=True, verbose_name='Descripición'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='ingredients',
            field=models.ManyToManyField(related_name='pizza', to='pizzas.Ingredient', verbose_name='Ingredientes'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
